/* ===================================================================
   MASTER DATA ("Dictionary")
   Yeh sabhi tutors ke liye data ka srot hai.
=================================================================== */

const allTutors = [
  { 
    id: 1, 
    name: "Priya Sharma", 
    img: "https://randomuser.me/api/portraits/women/44.jpg", 
    location: "Rohini, Delhi, India", 
    rating: 4.5, 
    reviews: 128, 
    experience: 5, 
    subjects: ["Math", "Science"], 
    genderIcon: "👩‍🏫", 
    isPopular: true,
    // --- Naya Profile Data ---
    qualification: "M.Sc (Physics), B.Ed",
    bio: "Passionate physics and math tutor with 5 years of experience. I make complex concepts simple and fun! My students regularly score 95%+.",
    contact: { phone: "+91 9876543210", email: "priya.sharma@fintutor.com" },
    availability: "Mon-Fri (5 PM - 8 PM), Sat (10 AM - 1 PM)",
    fees: "₹800/hr (Online)",
    languages: ["Hindi", "English"],
    grades: ["Class 9", "Class 10", "Class 11 (Physics)", "Class 12 (Physics)"],
    certifications: ["CBSE Certified Educator", "Olympiad Coach"],
    stats: { successRate: "98%", students: 128, rating: 4.5 },
    demo_video: "https://www.youtube.com/embed/g1v_EfuE-M8", // Physics demo
    linkedin: "https://linkedin.com/in/priyasharma"
  },
  { 
    id: 2, 
    name: "Rahul Mehta", 
    img: "https://randomuser.me/api/portraits/men/32.jpg", 
    location: "Andheri, Mumbai, India", 
    rating: 5.0, 
    reviews: 95, 
    experience: 3, 
    subjects: ["English", "SST"], 
    genderIcon: "👨‍🏫", 
    isPopular: true,
    // --- Naya Profile Data ---
    qualification: "M.A (English Lit), B.Ed",
    bio: "I am an English and Social Studies specialist. I focus on building strong reading, writing, and critical thinking skills.",
    contact: { phone: "+91 9888877777", email: "rahul.mehta@fintutor.com" },
    availability: "Tue-Sat (6 PM - 9 PM)",
    fees: "₹600/hr",
    languages: ["English", "Hindi", "Marathi"],
    grades: ["Class 6", "Class 7", "Class 8", "Class 9", "Class 10"],
    certifications: ["IELTS Trainer", "ICSE Board Examiner"],
    stats: { successRate: "99%", students: 95, rating: 5.0 },
    demo_video: "https://www.youtube.com/embed/z-eBfmq-B-g", // English demo
    linkedin: "https://linkedin.com/in/rahulmehta"
  },
  { 
    id: 3, 
    name: "Sneha Verma", 
    img: "https://randomuser.me/api/portraits/women/65.jpg", 
    location: "Indiranagar, Bangalore, India", 
    rating: 4.5, 
    reviews: 143, 
    experience: 7, 
    subjects: ["Physics", "Chemistry"], 
    genderIcon: "👩‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "B.Tech (Chemical Eng), M.Sc (Chem)",
    bio: "Experienced tutor with a knack for making Chemistry reactions and Physics laws easy to understand. Special focus on NEET/JEE prep.",
    contact: { phone: "+91 9776543210", email: "sneha.verma@fintutor.com" },
    availability: "Mon-Sat (4 PM - 7 PM)",
    fees: "₹1000/hr (JEE/NEET)",
    languages: ["English", "Hindi", "Kannada"],
    grades: ["Class 11", "Class 12", "JEE Mains", "NEET"],
    certifications: ["NEET Certified Mentor", "JEE Advanced Coach"],
    stats: { successRate: "96%", students: 143, rating: 4.5 },
    demo_video: "https://www.youtube.com/embed/g1v_EfuE-M8", // Reusing demo
    linkedin: "https://linkedin.com/in/snehaverma"
  },
  { 
    id: 4, 
    name: "Amit Roy", 
    img: "https://randomuser.me/api/portraits/men/45.jpg", 
    location: "Salt Lake, Kolkata, India", 
    rating: 3.5, 
    reviews: 67, 
    experience: 4, 
    subjects: ["Accounts", "Business"], 
    genderIcon: "👨‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "M.Com, CA Finalist",
    bio: "Commerce specialist focused on building a strong foundation in Accountancy and Business Studies. Practical, real-world examples.",
    contact: { phone: "+91 9665544333", email: "amit.roy@fintutor.com" },
    availability: "Mon-Fri (7 PM - 10 PM)",
    fees: "₹700/hr",
    languages: ["English", "Hindi", "Bengali"],
    grades: ["Class 11 (Commerce)", "Class 12 (Commerce)", "B.Com"],
    certifications: ["Tally Certified", "GST Practitioner"],
    stats: { successRate: "92%", students: 67, rating: 3.5 },
    demo_video: "https://www.youtube.com/embed/z-eBfmq-B-g", // Reusing demo
    linkedin: "https://linkedin.com/in/amitroy"
  },
  { 
    id: 5, 
    name: "Divya Kaur", 
    img: "https://randomuser.me/api/portraits/women/68.jpg", 
    location: "Sector 22, Chandigarh, India", 
    rating: 5.0, 
    reviews: 210, 
    experience: 6, 
    subjects: ["Biology", "Chemistry"], 
    genderIcon: "👩‍🏫", 
    isPopular: true,
    // --- Naya Profile Data ---
    qualification: "M.Sc (Botany), B.Ed",
    bio: "Biology expert for NEET aspirants. I use mnemonics, diagrams, and regular tests to ensure students remember every detail.",
    contact: { phone: "+91 9554433221", email: "divya.kaur@fintutor.com" },
    availability: "Mon-Sun (5 PM - 8 PM)",
    fees: "₹900/hr (NEET)",
    languages: ["English", "Hindi", "Punjabi"],
    grades: ["Class 11 (Biology)", "Class 12 (Biology)", "NEET"],
    certifications: ["NEET Biology Expert", "CBSE Certified"],
    stats: { successRate: "97%", students: 210, rating: 5.0 },
    demo_video: "https://www.youtube.com/embed/g1v_EfuE-M8", // Reusing demo
    linkedin: "https://linkedin.com/in/divyakaur"
  },
  { 
    id: 6, 
    name: "Karan Singh", 
    img: "https://randomuser.me/api/portraits/men/51.jpg", 
    location: "Malviya Nagar, Jaipur, India", 
    rating: 3.5, 
    reviews: 39, 
    experience: 2, 
    subjects: ["Computer", "Coding"], 
    genderIcon: "👨‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "B.Tech (CS)",
    bio: "Software developer and coding enthusiast. I teach Python, Java, and Web Development (HTML/CSS/JS) from scratch. Project-based learning.",
    contact: { phone: "+91 9443322110", email: "karan.singh@fintutor.com" },
    availability: "Weekends (10 AM - 6 PM)",
    fees: "₹1000/hr (Coding)",
    languages: ["English", "Hindi"],
    grades: ["Class 9 (CS)", "Class 10 (CS)", "Class 11 (CS)", "Class 12 (CS)", "B.Tech"],
    certifications: ["Python Certified (PCEP)", "Full-Stack Developer"],
    stats: { successRate: "95%", students: 39, rating: 3.5 },
    demo_video: "https://www.youtube.com/embed/z-eBfmq-B-g", // Reusing demo
    linkedin: "https://linkedin.com/in/karansingh"
  },
  // --- Adding placeholder data for the rest ---
  { 
    id: 7, 
    name: "Meena Joshi", 
    img: "https://randomuser.me/api/portraits/women/12.jpg", 
    location: "Gomti Nagar, Lucknow, India", 
    rating: 4.5, 
    reviews: 156, 
    experience: 8, 
    subjects: ["Hindi", "Sanskrit"], 
    genderIcon: "👩‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "M.A (Hindi), M.A (Sanskrit)",
    bio: "Experienced teacher for Hindi and Sanskrit. Strong focus on grammar and literature for board exams.",
    contact: { phone: "+91 9332211009", email: "meena.joshi@fintutor.com" },
    availability: "Mon-Fri (4 PM - 7 PM)",
    fees: "₹500/hr",
    languages: ["Hindi", "English", "Sanskrit"],
    grades: ["Class 6", "Class 7", "Class 8", "Class 9", "Class 10"],
    certifications: ["CBSE Hindi Examiner", "Sanskrit Praveen"],
    stats: { successRate: "96%", students: 156, rating: 4.5 },
    demo_video: "https://www.youtube.com/embed/g1v_EfuE-M8", // Reusing demo
    linkedin: "https://linkedin.com/in/meenajoshi"
  },
  { 
    id: 8, 
    name: "Suresh Patel", 
    img: "https://randomuser.me/api/portraits/men/29.jpg", 
    location: "Maninagar, Ahmedabad, India", 
    rating: 5.0, 
    reviews: 201, 
    experience: 10, 
    subjects: ["Maths"], 
    genderIcon: "👨‍🏫", 
    isPopular: true,
    // --- Naya Profile Data ---
    qualification: "M.Sc (Maths), B.Ed",
    bio: "10 years of experience in teaching Mathematics. I make maths easy for everyone, from basic to advanced levels.",
    contact: { phone: "+91 9221100998", email: "suresh.patel@fintutor.com" },
    availability: "Mon-Sat (6 PM - 9 PM)",
    fees: "₹900/hr",
    languages: ["Gujarati", "Hindi", "English"],
    grades: ["Class 9", "Class 10", "Class 11", "Class 12", "JEE"],
    certifications: ["JEE Maths Mentor", "Gujarat Board Expert"],
    stats: { successRate: "98%", students: 201, rating: 5.0 },
    demo_video: "https://www.youtube.com/embed/z-eBfmq-B-g", // Reusing demo
    linkedin: "https://linkedin.com/in/sureshpatel"
  },
  { 
    id: 9, 
    name: "Anjali Nair", 
    img: "https://randomuser.me/api/portraits/women/21.jpg", 
    location: "Vyttila, Kochi, India", 
    rating: 4.5, 
    reviews: 88, 
    experience: 6, 
    subjects: ["English"], 
    genderIcon: "👩‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "M.A (English), B.Ed",
    bio: "Certified English teacher with a focus on ICSE and CBSE curriculum. Specializes in creative writing and public speaking.",
    contact: { phone: "+91 9110099887", email: "anjali.nair@fintutor.com" },
    availability: "Mon-Fri (4 PM - 7 PM)",
    fees: "₹600/hr",
    languages: ["English", "Malayalam", "Hindi"],
    grades: ["Class 8", "Class 9", "Class 10", "Spoken English"],
    certifications: ["ICSE English Examiner", "Spoken English Trainer"],
    stats: { successRate: "95%", students: 88, rating: 4.5 },
    demo_video: "https://www.youtube.com/embed/g1v_EfuE-M8", // Reusing demo
    linkedin: "https://linkedin.com/in/anjalinair"
  },
  { 
    id: 10, 
    name: "Ravi Kumar", 
    img: "https://randomuser.me/api/portraits/men/61.jpg", 
    location: "Banjara Hills, Hyderabad, India", 
    rating: 3.5, 
    reviews: 54, 
    experience: 4, 
    subjects: ["Science"], 
    genderIcon: "👨‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "B.Sc, B.Ed",
    bio: "General Science teacher for middle school. I use practical experiments and projects to make learning fun.",
    contact: { phone: "+91 9009988776", email: "ravi.kumar@fintutor.com" },
    availability: "Mon-Sat (5 PM - 8 PM)",
    fees: "₹400/hr",
    languages: ["Telugu", "Hindi", "English"],
    grades: ["Class 6", "Class 7", "Class 8"],
    certifications: ["State Board Certified", "Science Olympiad Coach"],
    stats: { successRate: "93%", students: 54, rating: 3.5 },
    demo_video: "https://www.youtube.com/embed/z-eBfmq-B-g", // Reusing demo
    linkedin: "https://linkedin.com/in/ravikumar"
  },
  { 
    id: 11, 
    name: "Pooja Shah", 
    img: "https://randomuser.me/api/portraits/women/33.jpg", 
    location: "Navrangpura, Ahmedabad, India", 
    rating: 4.5, 
    reviews: 112, 
    experience: 5, 
    subjects: ["Commerce", "Economics"], 
    genderIcon: "👩‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "M.Com (Economics)",
    bio: "Economics and Commerce tutor with a deep understanding of market trends and theories. Simplified learning for all boards.",
    contact: { phone: "+91 8998877665", email: "pooja.shah@fintutor.com" },
    availability: "Mon-Fri (6 PM - 9 PM)",
    fees: "₹750/hr",
    languages: ["Gujarati", "Hindi", "English"],
    grades: ["Class 11 (Commerce)", "Class 12 (Commerce)", "Economics"],
    certifications: ["GST Certified", "CBSE Economics"],
    stats: { successRate: "96%", students: 112, rating: 4.5 },
    demo_video: "https://www.youtube.com/embed/g1v_EfuE-M8", // Reusing demo
    linkedin: "https://linkedin.com/in/poojashah"
  },
  { 
    id: 12, 
    name: "Arjun Das", 
    img: "https://randomuser.me/api/portraits/men/77.jpg", 
    location: "Alipore, Kolkata, India", 
    rating: 5.0, 
    reviews: 134, 
    experience: 7, 
    subjects: ["History", "Civics"], 
    genderIcon: "👨‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "M.A (History)",
    bio: "History enthusiast who loves telling stories. I make History and Civics engaging and easy to remember for ICSE/CBSE students.",
    contact: { phone: "+91 8887766554", email: "arjun.das@fintutor.com" },
    availability: "Tue-Sun (5 PM - 8 PM)",
    fees: "₹550/hr",
    languages: ["Bengali", "English", "Hindi"],
    grades: ["Class 7", "Class 8", "Class 9", "Class 10"],
    certifications: ["ICSE History Examiner", "UPSC Prep Mentor"],
    stats: { successRate: "97%", students: 134, rating: 5.0 },
    demo_video: "https://www.youtube.com/embed/z-eBfmq-B-g", // Reusing demo
    linkedin: "https://linkedin.com/in/arjundas"
  },
  { 
    id: 13, 
    name: "Amit Kumar", 
    img: "https://randomuser.me/api/portraits/men/33.jpg", 
    location: "Gomti Nagar, Lucknow, India", 
    rating: 4.0, 
    reviews: 80, 
    experience: 6, 
    subjects: ["Physics", "Math"], 
    genderIcon: "👨‍🏫", 
    isPopular: true,
    // --- Naya Profile Data ---
    qualification: "M.Sc (Physics), B.Ed",
    bio: "Physics and Math tutor based in Lucknow. I provide personalized attention and clear all doubts.",
    contact: { phone: "+91 8776655443", email: "amit.kumar@fintutor.com" },
    availability: "Mon-Fri (6 PM - 9 PM)",
    fees: "₹700/hr",
    languages: ["Hindi", "English"],
    grades: ["Class 9", "Class 10", "Class 11 (Physics)"],
    certifications: ["UP Board Certified", "IIT-JEE Mentor"],
    stats: { successRate: "94%", students: 80, rating: 4.0 },
    demo_video: "https://www.youtube.com/embed/g1v_EfuE-M8", // Reusing demo
    linkedin: "https://linkedin.com/in/amitkumar"
  },
  { 
    id: 14, 
    name: "Neha Verma", 
    img: "https://randomuser.me/api/portraits/women/45.jpg", 
    location: "Banjara Hills, Hyderabad, India", 
    rating: 4.8, 
    reviews: 110, 
    experience: 4, 
    subjects: ["Biology", "Chemistry"], 
    genderIcon: "👩‍🏫", 
    isPopular: true,
    // --- Naya Profile Data ---
    qualification: "B.Pharm, M.Sc (Chemistry)",
    bio: "Friendly and approachable tutor for Biology and Chemistry. Strong foundation for medical entrance exams.",
    contact: { phone: "+91 8665544332", email: "neha.verma@fintutor.com" },
    availability: "Mon-Sat (5 PM - 8 PM)",
    fees: "₹850/hr",
    languages: ["Telugu", "English", "Hindi"],
    grades: ["Class 10", "Class 11", "Class 12", "NEET"],
    certifications: ["NEET Coach", "State Board Topper"],
    stats: { successRate: "97%", students: 110, rating: 4.8 },
    demo_video: "https://www.youtube.com/embed/z-eBfmq-B-g", // Reusing demo
    linkedin: "https://linkedin.com/in/nehaverma"
  },
  { 
    id: 15, 
    name: "Sanjay Verma", 
    img: "https://randomuser.me/api/portraits/men/37.jpg", 
    location: "Sector 15, Gurugram, India", 
    rating: 4.1, 
    reviews: 61, 
    experience: 5, 
    subjects: ["Math", "Science"], 
    genderIcon: "👨‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "B.Tech (Mechanical)",
    bio: "Engineer with a passion for teaching. I help students build a strong base in Math and Science for future competitive exams.",
    contact: { phone: "+91 8554433221", email: "sanjay.verma@fintutor.com" },
    availability: "Weekends (10 AM - 4 PM)",
    fees: "₹700/hr",
    languages: ["Hindi", "English"],
    grades: ["Class 8", "Class 9", "Class 10"],
    certifications: ["Olympiad Coach", "NTSE Mentor"],
    stats: { successRate: "93%", students: 61, rating: 4.1 },
    demo_video: "https://www.youtube.com/embed/g1v_EfuE-M8", // Reusing demo
    linkedin: "https://linkedin.com/in/sanjayverma"
  },
  { 
    id: 16, 
    name: "Suresh Patel", // Duplicate name, different person
    img: "https://randomuser.me/api/portraits/men/34.jpg", 
    location: "Vastrapur, Ahmedabad, India", 
    rating: 4.2, 
    reviews: 72, 
    experience: 8, 
    subjects: ["Math", "Science"], 
    genderIcon: "👨‍🏫", 
    isPopular: false,
    // --- Naya Profile Data ---
    qualification: "M.Sc (Maths), B.Ed",
    bio: "Senior Mathematics and Science teacher with 8 years of experience in Gujarat board. Clear concepts guaranteed.",
    contact: { phone: "+91 8443322110", email: "s.patel@fintutor.com" },
    availability: "Mon-Fri (5 PM - 8 PM)",
    fees: "₹650/hr",
    languages: ["Gujarati", "Hindi"],
    grades: ["Class 9", "Class 10 (GSEB)"],
    certifications: ["GSEB Board Examiner", "Maths Expert"],
    stats: { successRate: "94%", students: 72, rating: 4.2 },
    demo_video: "https://www.youtube.com/embed/z-eBfmq-B-g", // Reusing demo
    linkedin: "https://linkedin.com/in/sureshpatel2"
  }
];
